[db]
35.183.45.254 ansible_user=ubuntu
3.96.222.149 ansible_user=ubuntu
15.223.4.15 ansible_user=ubuntu

[mtn]
3.98.122.61 ansible_user=ec2-user
3.99.150.229 ansible_user=ec2-user
35.183.101.21 ansible_user=ec2-user

[dev-web]
15.223.76.194 ansible_user=ec2-user
35.182.248.81 ansible_user=ec2-user
3.96.176.20 ansible_user=ec2-user
15.223.209.165 ansible_user=ec2-user
35.183.182.224 ansible_user=ec2-user
3.98.144.172 ansible_user=ec2-user

[all:vars]
ansible_ssh_private_key_file=~/.ssh/sept23.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'