[db]
3.96.171.7 ansible_user=ubuntu
3.99.138.168 ansible_user=ubuntu
35.183.45.137 ansible_user=ubuntu

[mtn]
99.79.67.205 ansible_user=ec2-user
3.99.213.155 ansible_user=ec2-user
99.79.49.252 ansible_user=ec2-user

[all:vars]
ansible_ssh_private_key_file=~/.ssh/sept23.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'